### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by easella** [sysce/proxy#4] opened 2021-03-02 21:51 UTC
there is a syntax error

**Comment by deopdeop** [comment] 2021-03-03 13:56
Are you going to at least show the error?

**Comment by easella** [comment] 2021-03-26 22:11
yeah. here is the error.
![image](https://user-images.githubusercontent.com/74786054/112697741-9dc5fb80-8e5e-11eb-8916-bb5be86e004b.png)

**Comment by e9x** [comment] 2021-04-02 18:06
Make sure to install all the modules with `npm i`

**Comment by easella** [comment] 2021-04-02 20:38
I did

**Comment by e9x** [comment] 2021-04-03 01:10
Try to run `npm install sys-nodehttp` , see if that installs the dependency.

**Comment by easella** [comment] 2021-04-03 20:15
i did and it still does not work. 
click the link here:[](https://replit.com/@awdrgyjil1234/PushyGoodSignature#main.sh)

**Comment by easella** [comment] 2021-04-07 21:21
please fix it.

**Comment by e9x** [comment] 2021-04-07 21:27
Misclick mb

**Comment by easella** [comment] 2021-04-07 21:34
I really wanna play wings io

**Comment by easella** [comment] 2021-04-07 21:35
Can you look at the code here. Please?
[click here](https://replit.com/@awdrgyjil1234/PushyGoodSignature#main.sh)
Then fork the project, fix the syntax error, and put the link in the comments.

**Comment by e9x** [comment] 2021-04-07 21:47
sys-proxy runs on sys-nodehttp v1.5.1, run `npm i sys-nodehttp@1.5.1`

**Comment by easella** [comment] 2021-04-07 22:57
I did and it simply shows this.
![image](https://user-images.githubusercontent.com/74786054/113944735-0c964380-97d3-11eb-8bc0-7b89157650d8.png)

**Comment by e9x** [comment] 2021-04-09 13:10
I don't see any errors in the screenshot provided?

**Comment by easella** [comment] 2021-04-09 15:27
I think the error is in config.json. the address cannot be found.

**Comment by easella** [comment] 2021-04-12 13:29
ok here it is with the error.
![image](https://user-images.githubusercontent.com/74786054/114402130-89c60d80-9b71-11eb-9ee9-d7a70380c4b9.png)

**Comment by e9x** [comment] 2021-04-12 14:54
unsure why the server is listening on 1.1.1.1, most likely an issue on your end

**Comment by e9x** [comment] 2021-04-12 15:02
update your config, listen on "0.0.0.0"

**Comment by easella** [comment] 2021-04-12 15:12
I did and it still does not work.
![image](https://user-images.githubusercontent.com/74786054/114417849-f6480900-9b7f-11eb-9b9c-9da3f0956781.png)

**Comment by e9x** [comment] 2021-04-12 15:46
try the ports:
80, 8080, 443

disable the SSL option in the config so 
"ssl": false

**Comment by easella** [comment] 2021-04-12 15:54
I did that and it still does not work.
![image](https://user-images.githubusercontent.com/74786054/114424155-d74c7580-9b85-11eb-8c1e-97cf46cf9d1e.png)

**Comment by e9x** [comment] 2021-04-12 15:55
Don't put "false" in quotes, replace the ssl line with

`"ssl": false`

**Comment by easella** [comment] 2021-04-12 15:56
I did and nit does not work

**Comment by e9x** [comment] 2021-04-12 15:57
```
{
"port": 8080,
"address": "0.0.0.0",
"ssl": false
}
```

**Comment by easella** [comment] 2021-04-12 15:59
it does not work.
![image](https://user-images.githubusercontent.com/74786054/114424831-7d987b00-9b86-11eb-981e-b0568ddf0914.png)

**Comment by e9x** [comment] 2021-04-12 16:13
cant see the full error

**Comment by easella** [comment] 2021-04-12 16:14
here is the full error.
![image](https://user-images.githubusercontent.com/74786054/114427031-ad488280-9b88-11eb-8631-c09f8ac4f6a0.png)

**Comment by e9x** [comment] 2021-04-12 16:15
okay set ssl to `null`

```
"ssl": null
```

**Comment by easella** [comment] 2021-04-12 16:32
does not work
![image](https://user-images.githubusercontent.com/74786054/114429284-306ad800-9b8b-11eb-8fac-499d4c4cee31.png)

**Comment by e9x** [comment] 2021-04-12 16:35
would appear to be an issue with the public source, I have been focusing development to the full-js branch and I do not want to update the master branch just to merge the full-js one and lose work

**Comment by easella** [comment] 2021-04-12 17:20
what do you mean?

**Comment by easella** [comment] 2021-04-12 19:39
so you will not fix the error?

**Comment by e9x** [comment] 2021-04-12 19:48
no?

**Comment by easella** [comment] 2021-04-12 20:42
can you please fix the error?

**Comment by e9x** [comment] 2021-04-12 20:44
I've already answered this, no I will not be fixing the error on the master branch. Assuming there will be no further progress in this issue, I am closing it.

**Closed by e9x** 2021-04-12 20:44 UTC

**Comment by easella** [comment] 2021-04-12 20:45
Please?

**Comment by e9x** [comment] 2021-04-12 20:50
The script functions, just not on replit.

**Comment by easella** [comment] 2021-04-12 20:51
where does it function?

**Comment by e9x** [comment] 2021-04-12 20:57
What?

**Comment by easella** [comment] 2021-04-12 20:57
I said what coding app does the script work on?

**Comment by easella** [comment] 2021-04-12 20:58
does it work on heroku.com, codesandbox.io, or glitch.me?

**Comment by e9x** [comment] 2021-04-12 21:00
If the platform supports nodejs then the script should function. With the services you listed it depends on if those recognize scripts running with the https protocol (which disabling does not work as intended on the master branch).

**Comment by easella** [comment] 2021-04-12 21:01
it works with none of those apps. what do I do?

**Comment by e9x** [comment] 2021-04-12 21:02
Host the script locally or on a server you have access to.

**Comment by easella** [comment] 2021-04-12 21:04
what do you mean?

**Comment by e9x** [comment] 2021-04-12 21:05
If you cannot do either then hosting a proxy script (at least sysce/proxy) is not possible for you.

**Comment by easella** [comment] 2021-04-12 21:05
how could I locally host it?

**Comment by e9x** [comment] 2021-04-12 21:07
For that you would need access to a terminal and have nodejs installed on your machine. I have just pushed a commit fixing the SSL issue, if you still want to attempt to run the script then update to the latest.

**Comment by easella** [comment] 2021-04-12 21:07
is it possible on a school chromebook?

**Comment by e9x** [comment] 2021-04-12 21:08
If you have access to linux beta then yes.

**Comment by easella** [comment] 2021-04-12 21:13
I dont.

**Comment by e9x** [comment] 2021-04-12 21:14
🤷‍♂️ You are welcome to try the latest commit on repl.it.

**Comment by easella** [comment] 2021-04-12 21:14
what commit?

**Comment by e9x** [comment] 2021-04-12 21:15
39343774de3bdc2d2350b186b435b54ab6f7ca0d

**Comment by easella** [comment] 2021-04-12 21:20
thank you so much! it works!

**Comment by e9x** [comment] 2021-04-12 21:22
👍

**Comment by easella** [comment] 2021-04-12 21:24
the heroku demo still does not work.it still says application error.
